version: '3'

services:

  php:
    build: ./php
    image: app_php:7.3-fpm
    container_name: php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./laravel:/var/www
    networks:
      - app-network

  nginx:
    build: ./nginx
    image: app_nginx:1.17.4
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./laravel:/var/www
    networks:
      - app-network
    depends_on:
      - php

  mysql:
    build: ./mysql
    image: app_mysql:5.7.22
    container_name: mysql
    restart: always    
    ports:
      - 3307:3306    
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - mysql-volume:/var/lib/mysql/
    networks:
      - app-network


 # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mysql
  #     - PMA_USER=user
  #     - PMA_PASSWORD=pass
  #   links:
  #     - mysql
  #   ports:
  #       - 8080:80
  #   volumes:
  #       - ./docker/phpmyadmin/sessions:/sessions
  #       - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

  networks:
   app-network:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
